version: "3.7"

services:   

  servicename-dev:
    image: node:20-alpine
    container_name: containernamedev
    restart: always
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "3008:4003"  
    command: npm run dev
    
