version: "3.7"

services:   

  apigatewaybackend-prod:
    build:
      context: .
      dockerfile: dockerFile-prod
    container_name: apigatewaybackendprod
    restart: always 
    depends_on:
      - apigateway-db-prod
    env_file:
      - .env.prod  
    networks:
      - lingoage-microservice-network-prod

  


networks:
  lingoage-microservice-network-prod:
    external: true

