FROM node:20-alpine as dependencies
WORKDIR /my-project
COPY package.json ./
RUN npm install

FROM node:20-alpine as builder
WORKDIR /my-project
COPY . .
COPY --from=dependencies /my-project/node_modules ./node_modules
RUN npm run build

FROM node:20-alpine as runner
WORKDIR /my-project
ENV NODE_ENV production
# If you are using a custom next.config.js file, uncomment this line.
# COPY --from=builder /my-project/next.config.js ./

COPY --from=builder /my-project/dist ./dist

COPY --from=builder /my-project/.env.prod ./.env.prod
COPY --from=builder /my-project/node_modules ./node_modules
COPY --from=builder /my-project/package.json ./package.json

EXPOSE 6008
CMD ["npm", "run","start"]